### ISSUE TITLE
UX buttons: Manual SDKInstaller window 

### ISSUE THREAD

**Issue by kfrajer** [DeerajTheepshi/processing-android#12]
I suggest the following changes:

-The button "Continue" should be renamed "Install" meaning "Install now"
-This button should be the first from left to right
-Only truncate longer folder paths (Red square)
-To discuss, to drop the cancel button and to leave only two: "Install" and "back"

![SDKinstaller_selection](https://user-images.githubusercontent.com/26076840/59582112-29650280-90a5-11e9-8468-22d8bc6788dc.png)

**Comment by DeerajTheepshi** [comment]
Sure @kfrajer , will do the changes and push soon.

Regd dropping cancel button : It seems to be a good option . Cause we don't want the users to start the Android Mode without and SDK. Is there any use case where, cancelling the installation would be useful [Afaik, no]?? @kfrajer

**Comment by kfrajer** [comment]
As it is right now, you can get into disabled Android Mode when the user cancels. That is the current intended behavior and I'd say it is fine as it is. Dropping the cancel means that the user can always go back in case it does not want to do the automatic installer. If he wants to cancel, he needs to go back and hit the x to close the window: "automatic install or locate path manually".
In other words, we do not need to manage this cancel state on this Window. If the user wants to cancel the operation, he should go back. That is my argument. What are your thoughts?

**Comment by DeerajTheepshi** [comment]
Yeah, it looks good to me too. Will do the changes

**Comment by DeerajTheepshi** [comment]
Solved using fc361dcee5f98acc9a2d80829f6e9ddf0cbc2c6b.

Close the issue if you feel this is fine, @kfrajer
