### ISSUE TITLE
Windows10: It fails installing AndroidSDK

### ISSUE THREAD

**Issue by kfrajer** [DeerajTheepshi/processing-android#13]
While testing the whole flow for the Android SDK installer, I notice that when selecting the "automatic" installer, the progress bar gets stuck at 78% and it never finishes throwing an error: *Installation cancel by user, Android mode has been disabled*. 

Tested in Windows 10 and P3 version 0270.

**Next step**:
-Figure out if it fails in downloading resource's step, if it fails when finishing the unpacking and re-arranging the folders or some sort of timeout issue.

**Comment by DeerajTheepshi** [comment]
@kfrajer , This is something I have seen earlier. Andres fixed it once. I can do it, shall I take it up (I can see that you self assigned yourself, does that mean you will look into it) ? 

Previous occurences: 
https://github.com/processing/processing-android/issues/421
https://github.com/processing/processing-android/issues/418

**Comment by kfrajer** [comment]
Yes, I can look into this more like at the end of the week and I will report here

**Comment by kfrajer** [comment]
The first link could be related but not solution was offered beside installing the SDK manually. The second link was solved by a commit. The current problem is probably with the implementation of the installation flow. Further testing indicates a second glitch whci I will be reporting shortly.

When installation it fails (either canceled by user or failed downloading/installing a component (?) ), there is a flag that is raised to indicate the Android mode is disabled, correct? 
1. What is the line of this flag in the code? 
2. Do you know if this flag is saved in the preferences.txt file?

**Comment by kfrajer** [comment]
@DeerajTheepshi 
The 78% error is proven hard to debug. I have some questions:
- The progress bar updates based on the total values of downloaded files, correct? Can it indirectly trigger the message "AM disabled" in the case it did not register all the bytes? Or if the bytes goes above the total size initially registered?
- All files has been downloaded and they have a size. Not sure if the error is in the unpacking. I am suspicious of haxm or probly the usdDriver. When I check the sdk folder, extraFolders has the Intel folder but it is empty.
- Current error messages do not help. It does not help that the download+unpacking+installation is done all in the same process either.
- Do you have a strategy to debug this in case of dealing with different OS's an platforms?
- This is the content of urlHolder after it fails with this 78% error. Do you see anything that is not correct? I have done a bit of analysis to see which file is at the 78% download mark but it seems this is not captured here... maybe there are more files being processed? [report-u01.txt](https://github.com/DeerajTheepshi/processing-android/files/3317186/report-u01.txt)

**Comment by kfrajer** [comment]
I did the whole install flow using the current `upstream master` branch instead and it seems this issue was also present in that branch.
- I was able to partially resolved the issue in `upstream/master` by downloading haxm and usbDriver zip files manually and placing them in the temp folder. 
- This is probably the same issue in the `Milestone1 branch` repo **plus** there is a second issue. As you see in the report in my prev msg, the installer downloaded linux packages when I am in a Windows OS. To summarize:
  - `Milestone1` branch downloaded:
    - build-tools_r29-linux.zip
    - platform-29_r01.zip
    - platform-tools_r29.0.1-darwin.zip
    - sdk-tools-darwin-4333796.zip
  - `Upstream/master` downloaded:
    - build-tools_r26.0.3-windows.zip
    - emulator-windows-5598178.zip  **(Skipped)**
    - haxm-windows_v7_5_1.zip  **(Manual)**
    - platform-26_r02.zip
    - platform-tools_r29.0.1-windows.zip
    - sdk-tools-windows-4333796.zip
    - usb_driver_r11-windows.zip **(Manual)**

I will investigate further why the OS/platform is not properly inferred in my system. The second step is to figure out why the haxm/usbDriver are not being downloaded.

**Comment by DeerajTheepshi** [comment]
@kfrajer , I read through the code today along with the file that you sent me, and found out the reasons for the above : 
-  **Stopped at 78%** :  downloadAndUnpack()  function was called upon emulator, which is null (I did not remove it) . This was the reason why usb driver and HAXM also wasn't installed .
-  There was also an error with the download url of tools. 
- I have fixed these . I also added some comments that is useful for future reuse of code.

Fixed using 385f11f92ca2de0416362406c05c4cc77cd5c2bb.

The install process runs completely now. (Tested on Win10 and Arch Linux.)

**Comment by kfrajer** [comment]
In reference to recent commit: [385f11f92ca2de0416362406c05c4cc77cd5c2bb](https://github.com/DeerajTheepshi/processing-android/commit/385f11f92ca2de0416362406c05c4cc77cd5c2bb):

-----------
Hi @DeerajTheepshi ,
I found the issue with choosing the right packages. File sizes and names are coming from `https://dl.google.com/android/repository/repository2-1.xml` and are processed by [parseURL](https://github.com/DeerajTheepshi/processing-android/blob/android-0274-v4.1.0-beta3/mode/src/processing/mode/android/SDKDownloader.java#L314) in SDKDownloader.java. However, you are choosing always the first item in the Array during this processing without taking into account the host OS information. I have added comments to [your recent commit](https://github.com/DeerajTheepshi/processing-android/commit/385f11f92ca2de0416362406c05c4cc77cd5c2bb#r34043434) where you address this 

I also noticed you fixed this, what it seems like a typo [here](https://github.com/DeerajTheepshi/processing-android/commit/385f11f92ca2de0416362406c05c4cc77cd5c2bb#r34043407). 

I am still investigating if this next section is interfering with the install of haxm or usbdriver. I notice this sections about ANDROID_REPO and GOOGLE_REPO were commented out [here](https://github.com/DeerajTheepshi/processing-android/blob/android-0274-v4.1.0-beta3/mode/src/processing/mode/android/SDKDownloader.java#L523). However, there are sections in the code that are calling these functions.  I checked upstream/master and these sections are disabled there as well.

**Comment by kfrajer** [comment]
It is not working for me and I think it is because of this hamx/usbDriver. Do you see the zip files for these components in your temp folder?  I commented the emulator lines from the start of this testing so I am sure that is not the problem. I am guessing the issue is either in the links for those resources for the Downloader to process or something wrong in the code logic that precedes the current changes.

**Comment by kfrajer** [comment]
@DeerajTheepshi  I was commenting out only one line of the two for the emu. Commenting out both solved the problem. You can close this issue when you do the commit about the extra `else` clause to rm repeated code. Great job!

**Comment by DeerajTheepshi** [comment]
> @DeerajTheepshi I was commenting out only one line of the two for the emu. Commenting out both solved the problem. You can close this issue when you do the commit about the extra `else` clause to rm repeated code. Great job!

I guess this whole issue was my mistake with typos and not removing the emulator code, sorry for the trouble. However, can you ask Andres why android_repo and google_repo are commented out?

**Comment by DeerajTheepshi** [comment]
Else block corrected and closed using 42d24e51a3f58ae99f795376b44c0c392caadf56
