### ISSUE TITLE
AndroidSDK installation workflow glitch #2

### ISSUE THREAD

**Issue by kfrajer** [DeerajTheepshi/processing-android#14]
### Intended behavior:
- The user launches the PDE in java mode
- The user switches to AM
- A popup asks if automatic or manual install
- User by error clicked manual installer. 
- A fileChooser is shown. The user clicks cancel
- A second message shows saying "AM is disabled"
- The user reverts to java mode
- The user then switches to Android mode (again)
- A popup asks if automatic or manual install
- The user clicks automatic install and then the Automatic Dialog menu shows up (***)

### Bug:
In the last step, the dialog does not show up but instead, the installation starts right away and the progress bar dialog box is shown immediately.

### Additional notes:
- Similar behavior is observed in other workflows. When a popup message with "Android Mode is disabled" appears, next time the Android installer flow is executed, it sometimes skips the automatic AndroidSDK installer's menuand launches the progress bar.
- Since this issue is observed even after restarting the PDE, I have the following theories:
  * Is there a state saved in the preference.txt file? 
  * The installer workflow is looking for the temp folder where the AndroidSDK download are stored
  * The Android SDK workflow takes into account the fields present in the preferences file. When a download is canceled, the preference files already have the following fields:
android.sdk.ar=1.2.0
android.sdk.gvr=1.150.0
android.sdk.play_services=11.0.4
android.sdk.support=26.0.2
android.sdk.target=26
android.sdk.wear=2.1.0
 
### Environment:
- OS: Microsoft Windows [Version 10.0.17763.557]
- Processing AM (First line "git log --pretty=oneline"):
 fc361dcee5f98acc9a2d80829f6e9ddf0cbc2c6b (HEAD -> android-0274-v4.1.0-beta3, dfork/android-0274-v4.1.0-beta3) [Fix] Remove cancel,Resize path
- Processing (First line "git log --pretty=oneline"):
37108add372272d7b1fc23d2500dce911c4d1098 (grafted, HEAD -> master, origin/master, origin/HEAD) attempt to use 8u212, but Oracle has broken the download

**Comment by DeerajTheepshi** [comment]
@kfrajer , 

Are you sure about the mode selection ? In case you have **two Android Modes** (The original and the development code) , you would have to select the Android Mode that corresponds to the dev code.

I'm asking this, as I tried to recreate the above mentioned bug, but however it works fine for me.  (Tested on Win10 and Arch Linux)

As far as preferences.txt is concerned : The installer only checks for the presence and validity of an SDK Path . The other details are set by default to the minimum Requirement by the static methods of AndroidBuild class and these details do not affect the behavior of the installer.

**Comment by kfrajer** [comment]
I captured it. I am still looking into the 78% download issue. Maybe you can give me some ideas of what I should look into first. Anyways, I am going hard on them tomorrow.

![glitch2](https://user-images.githubusercontent.com/26076840/59960140-94417f80-9491-11e9-9bf0-0fefc0ef2768.gif)

**Comment by DeerajTheepshi** [comment]
Yeah @kfrajer . As recorded, you are not selecting the android mode that corresponds to the dev code. You are selecting the one below the Java option which is your Original Android Mode. Select the one that is present at the bottom of the drop-down. That mode corresponds to our dev code and hence, that would work fine. (hopefully!)

**Comment by kfrajer** [comment]
Yes, you are right. Now I understood your message. I did not notice it. Closing this.
