### ISSUE TITLE
Testing of Android SDK installer on Mac 

### ISSUE THREAD

**Issue by kfrajer** [DeerajTheepshi/processing-android#15]
#### Summary:
Test the flow of Android SDK installer on Mac OS

#### Steps:
First, make sure the PDE is not running. Locate the Processing's preference.txt file (You can find it if you run the PDE and then go to *File>>Preferences* and the location of the preferences.txt file is at the bottom). Open this file and removes all lines related to Android settings as these lines are created by the intaller. An example of what you need to remove:

> android.sdk.ar=1.2.0
> android.sdk.gvr=1.150.0
> android.sdk.path=C:\Users\C\Documents\Processing\android\sdk
> android.sdk.play_services=11.0.4
> android.sdk.support=26.0.2
> android.sdk.target=26
> android.sdk.wear=2.1.0

There could be more lines and you can removes those ones as well. Before removing these lines, you can backup the file if you feel like doing so. 

Then start the PDE. If it starts in Android mode, switch to Java and follow the next steps:

* The user launches the PDE running in java mode
* The user switches to AM
* A popup appears asking if automatic or manual install
* User **by error** clicked on manual installer. 
* A fileChooser is shown. The user clicks **cancel** *(Relevant)*
* A second message shows saying **Android Mode is disabled**
* The user reverts to java mode
* The user then switches back to Android mode.
* A popup asks if automatic or manual install *(Relevant)*
* The user clicks automatic install and then the Automatic Dialog menu shows up  *(Relevant)*
* This dialog shows what it will be installed, location and a button to change it
* Please press the **back** button *(Relevant)*
* The simple menu automatic or manual install appears again 
* The user clicks automatic install and then the Automatic Dialog menu shows up
* Finally you click **install** (ensure there is not a previous SDK in that location **!!!**) and it will proceed to install (about 400MB) the required files including (Next for Windows):
--- platformToolsFilename: platform-tools_r29.0.1-darwin.zip
--- buildToolsFilename: build-tools_r29-linux.zip
--- platformFilename: platform-29_r01.zip
--- toolsFilename: sdk-tools-darwin-4333796.zip
--- usbDriverFilename: usb_driver_r11-windows.zip  *(Only for Win OS)*
--- haxmFilename: haxm-windows_v7_5_1.zip *(Only for Win OS)*

#### Report:
- Report any issues inn the steps above
- You should be able to run a simple sketch on a device (No emulator at the moment)

**Comment by sarahcodes100** [comment]
The changes look good! Here are a few edge cases I noticed:

https://github.com/DeerajTheepshi/processing-android/issues/16
https://github.com/DeerajTheepshi/processing-android/issues/17
https://github.com/DeerajTheepshi/processing-android/issues/18
https://github.com/DeerajTheepshi/processing-android/issues/19
https://github.com/DeerajTheepshi/processing-android/issues/20
https://github.com/DeerajTheepshi/processing-android/issues/21
https://github.com/DeerajTheepshi/processing-android/issues/22
