### ISSUE TITLE
Downloader should check if android dir exists

### ISSUE THREAD

**Issue by sarahcodes100** [DeerajTheepshi/processing-android#17]
If I already have an `android/` in Processing but have removed or renamed the sdk folders (here I renamed them as a test), the SDK downloader should:
1. download the SDKs into that existing dir
2. set it as the default directory from the SDK downloader UI

Here, you can see that after I selected my existing `android/`, it placed them into `android/android/sdk` instead of `android/sdk`

<img width="609" alt="detect-1" src="https://user-images.githubusercontent.com/494323/60032269-36b95880-9674-11e9-9a04-4328e023bbbf.png">
<img width="607" alt="detect-2" src="https://user-images.githubusercontent.com/494323/60032270-36b95880-9674-11e9-8e06-e5b1d1b7fff9.png">
<img width="618" alt="detect-3" src="https://user-images.githubusercontent.com/494323/60032271-36b95880-9674-11e9-903a-bfff72c557d9.png">

**Comment by kfrajer** [comment]
Yes, I think internally during the folder selection process, the user sets the path of the folder that will contain the android/sdk folder. The installer creates the `Android` folder and then it creates a `temp` folder there where it installs all the downloaded zip files. Next it creates a `sdk` folder where it installs the files. I agree that the installer dialog is not clear for this part.  This can be improved so the path shown in the dialog is the final path for the sdk folder. Say the user selects to install the sdk here:

`~/programfiles/extra/`

After the user selects the path above, the dialog installer should display 

 `~/programfiles/extra/Android/sdk/`

so the user gets to see the final destination. That would make the process more clear, right? @sarahlensing @DeerajTheepshi

**Comment by DeerajTheepshi** [comment]
@sarahlensing  The pde does check for existence of the android folder :https://github.com/DeerajTheepshi/processing-android/blob/d3803800cd9a6c150bac21bddd814927fef8df23/mode/src/processing/mode/android/SDKDownloader.java#L120 However as @kfrajer suggested it is not clearly explained to the user.

**Comment by DeerajTheepshi** [comment]
Fixed as per @kfrajer suggestion, using d3803800cd9a6c150bac21bddd814927fef8df23.

Close this issue if you feel its fine, @sarahlensing .

**Comment by kfrajer** [comment]
@DeerajTheepshi You redefine the [initial folder name](https://github.com/DeerajTheepshi/processing-android/commit/d3803800cd9a6c150bac21bddd814927fef8df23#diff-64083df747d169bc86ea23dd16e6be9aR737) but would it be an issue if this point does not exist? Just to confirm, did you test all the use cases for this change?
