### ISSUE TITLE
Should show better error message

### ISSUE THREAD

**Issue by sarahcodes100** [DeerajTheepshi/processing-android#20]
If I don't have the SDK installed and go into the "Locate SDK path manually" window and press "cancel" instead of selecting a path, this error message shows:

<img width="434" alt="null" src="https://user-images.githubusercontent.com/494323/60033356-6cf7d780-9676-11e9-9de3-92645718b1b6.png">

It should probably say something like "the SDK path could not be found" or "the SDK path is invalid"

**Comment by DeerajTheepshi** [comment]
Fixed using : 6e1dd0df387a710082e26f1644ca71a7810529fd
Close this issue , if it's fine. @sarahlensing
