### ISSUE TITLE
Using Emulators from AS

### ISSUE THREAD

**Issue by kfrajer** [DeerajTheepshi/processing-android#23]
As requested in this [Processing forum's post](https://discourse.processing.org/t/using-emulators/12262), to be able to access emulators defined in Android Studio from Processing.

**Key concept**: To use emulators already defined in Android Studio or to allow the user to setup the emulator home folder in the same location as defined by AS.

How to get the Android Emulator home folder?

**Comment by kfrajer** [comment]
#### Get the Android Emulator home folder: 

Possibly using [ANDROID_SDK_HOME](https://stackoverflow.com/questions/2841766/possible-to-change-where-android-virtual-devices-are-saved)

More about Android's environmental variables [here](https://developer.android.com/studio/command-line/variables)

[Start the emulator from the command line](https://developer.android.com/studio/run/emulator-commandline)

**Comment by DeerajTheepshi** [comment]
Will be included as part of the new emulator . 

Plan : To use “avdmamager list avd” this will list all avds irrespective of whether processing created it or AS. Later this will be shown to the user in the run configuration window (check emulator UI designs) .

**Comment by DeerajTheepshi** [comment]
Fixed by removeing env.clear()
