### ISSUE TITLE
SDK updater: cancel when installing a platfrom

### ISSUE THREAD

**Issue by kfrajer** [DeerajTheepshi/processing-android#26]
#### Issue:
When I use The SDK updater to install a platform, if I hit cancel, the installer cancels as intended but the install button does not change to install but to "Refresh" as you can see in the image next: https://i.imgur.com/UbJRjOE.png

#### Expected behavior:
When I click cancel, the button's content changes from refresh to install.

#### Note:
if I click refresh, I get a popup indicating "Not platform selected" and then the button's content reverts to "Install"

**Comment by kfrajer** [comment]
Notice that this is also observed when updating any item under the SDK tools.

**Comment by DeerajTheepshi** [comment]
Closed with c985406c8b4413f74345014a105652be8c712cce
You can close the issue if you are ok with the changes @kfrajer
