### ISSUE TITLE
Emulator listing different in AS and Processing Android

### ISSUE THREAD

**Issue by DeerajTheepshi** [DeerajTheepshi/processing-android#27]
Reports given by @kfrajer:

While testing creating devices, I am using the avdmanager CLI and the avdmanager UI from AS as a cross-reference. From my initial testing, they cannot see the newly created devices using the PDE's "Run Configuration" flow. This is my current setup that I have in my D: drive while initially managing emulators using AS:

a nexus5
a Pixel XL
Processing-phone
After I run the "Run Configuration" flow and after creating a coupled of emulators, I get the following in my C: drive from the PDE flow:

emu-alpha
emu-beta
Processing-phone
Both avdmanager CLI and UI (from AS) only shows nexus5, Pixel XL and Processing-phone. However, it seems the Pixel XL is corrupted as well as the Processing-phone as you can see in the image below.

**Comment by DeerajTheepshi** [comment]
@kfrajer, are you sure that both processing and Android Studio are using the same android SDK ? By this I mean are the SDK Path in Android Studio's SDK Manager the same as the ones used by processing ?


**My Testing reports** :  I'm able to see emulators in both Android Studio and PDE. However, since my SDK Path for AS and PDE are different, the emulators I created using PDE are shown corrupted as no System image for the chosen emulator is available in the SDK path pointed by Android Studio.

**Comment by kfrajer** [comment]
@DeerajTheepshi  An update. The Processing-phone is not corrupt. It happens I moved th epath by accident during the SDKupdater testing. I examined the Processing-phone.ini file and I noticed the path did not existed anymore.

**Comment by kfrajer** [comment]
Probly related to #23

**Comment by kfrajer** [comment]
I was investigating about this and I was able to find the origin of this issue. It is related to the `processBuilder` creating and the environmental variables available in this process. As you can see in [1], `env.clean()` is removing all env vars definitions. In the absence of env vars, **avdmanager** will use default values. In windows for instance, avd ini file swill be place in *%USER_HOME%\.android\avd*.

I was using this thread[2] where they discuss the folder where avdmanager fetches all the info. They discuss about having ANDROID_SDK_HOME set to the folder containing `.android\avd`. There is also a suggestion to setup ANDROID_AVD_HOME to the same location. While I was expecting the latter to be the appropriator variable to set, it did not work for me(Windows 10). However, the next modification solved the issue:

```java
     ProcessBuilder pb =
              new ProcessBuilder(sdk.getAvdManagerPath(), "list", "avd");
      Map<String, String> env = pb.environment();
      String tmpSdkHome=env.get("ANDROID_SDK_HOME");
      env.clear();
      if(tmpSdkHome!=null & tmpSdkHome.equals("")==false) env.put("ANDROID_SDK_HOME", tmpSdkHome);
      env.put("JAVA_HOME", Platform.getJavaHome().getCanonicalPath());
      env.put("ANDROID_SDK_HOME", "D:\\Users\\C");
      //env.put("ANDROID_AVD_HOME", "D:\\Users\\C");
      pb.redirectErrorStream(true);

      process = pb.start();
```

Another solution would be to remove `env.clear()` and instead, remove target environmental variables[2]. For example: `env.remove("OTHERVAR");`

Some clarifications:
My **Android SDK** is located at `D:\Program_Files\AndroidSDK\sdk`
My Android avd files (ini files) at `D:\Users\C\.android\avd`
The location of the folders associated to each emulator are placed in the same folder as above. So listing the content of `D:\Users\C\.android\avd` returns:

> Nexus_9_API_26.avd
> Pixel_3_XL_API_26.avd
> emi-echo
> emu-golf.avd
> Nexus_9_API_26.ini
> Pixel_3_XL_API_26.ini
> emi-echo.ini
> emu-golf.ini
> processing-phone.ini

Note above that the Processing-phone supporting files are located in the `Processing\android` folder.

This only covers listing the devices. This change would need to be added to all `processBuilders`.

[1] https://github.com/DeerajTheepshi/processing-android/blob/master/mode/src/processing/mode/android/AVD.java#L166
[2] https://www.codota.com/code/java/methods/java.lang.ProcessBuilder/environment

![emu_all_issue_p_resolved](https://user-images.githubusercontent.com/26076840/61999961-81c2f300-b09a-11e9-9833-4c50ca26b71e.png)

**Comment by DeerajTheepshi** [comment]
Fixed, thanks to @kfrajer!!
