### ISSUE TITLE
Emulator cannot be connected / Run in pr

### ISSUE THREAD

**Issue by DeerajTheepshi** [DeerajTheepshi/processing-android#28]
Reports given by @kfrajer : 

 I am also unable to run a sketch in any of the recently created devices (tried both emu-alpha and emu-beta NOTE: Processing-phone is not in the list) but it did not work. I get the following error (screenshot at the end):

Emulator process exited with status 1.
EmulatorController: Emulator never booted. NOT_RUNNING
Error while starting the emulator. (NOT_RUNNING)
Shutting down any existing adb server... Done.

![image](https://user-images.githubusercontent.com/5101112/61600884-a4937880-ac50-11e9-8bc0-c8118d9b30f9.png)

Emulator never booted error is being shown, because of which the sketch is never run.

**Comment by DeerajTheepshi** [comment]
@kfrajer can you send me the entire stack trace, so that I can get to know what exactly happened?

**Comment by kfrajer** [comment]
After I fixed this issue about the missing folder for the Processing-phone emulator, then emu-alpha and Processing-phone both show up in the "Run configuration" flow (I deleted emu-beta). However, I am unable to start the sketch. In summary:

If I tried to launch the Processing-phone, it works as it launches it. However, I get the following error: The APK file is missing

If I tried to launch the emu-alpha, it does not work at all and the emulator device not even starts. I will send you the logs for both via email.

**Comment by DeerajTheepshi** [comment]
Regarding the installation code flow :
- Initially the devices list is displayed in the combo box using : "avd list devices ", which is then parsed to be displayed on the combo box. 
- After that the images are displayed using : Initially, the ABI is decided based on processor . If intel-x86, if the platform is Mac-x86, other-wise Arm is chosen. After this the system-images are queried using "sdkmanger --list". It is then parsed and displayed in the table. Here download option downloads the image from the android repository, while the next option moves to the final screen.
- Avd is now created using the following command: **"avdmanager avd create -n <name> -d <device> -k<system-image> -c <SD-card-size> -p <processingSketchFolder/android/avd>"**
- After this while running the emulator, the avd name is written to preferences.txt file. (It is then used for future runs)(Hence even if a new session of processing is started, the previously use emulator will run)
- Emulator is put into run using the command  **"emulator -avd <avdName> -port <staticPort> -gpu <standardGpuFlag>"**

This is how the code flows in regard to the emulator image installation, avd creation and emulator startup.

**Comment by DeerajTheepshi** [comment]
I'm looking through the stacktrace right now. Will update you in a few hours.

**Comment by DeerajTheepshi** [comment]
@kfrajer Can you re-run your emulator using the run configuration window, and let me know which platform you ran your emulator on? 

From the stacktrace I'm able to understand that, the error is with the build process and not the emulator. Hence, the apk file was not created by the build process, and the apk could not be loaded in to the adb, hence shutting it down. 

**My testing:**  I ran the code with SDK Versions lower than platform 26. 
Why 26 ? Because, from the stack trace I am able to see that the build failed due to resources and hence the build-tools. We have set the build tools at a static 26.0.2.  So I tried to run the emulator in a lower SDK platform , ie.. android-22 (Lollipop)

**Results of the test:** I ended up with the same results and same stacktrace of your error.

So, can you please help me by re-testing the code with SDK >= 26 ? Also let me know about the platform that you ran it previously.

**Comment by kfrajer** [comment]
I believe I was using the lowest platform which is 21.

I have deleted the emu-alpha and created an emu-echo set with Pixel XL and image API28 x86. I run by selecting platform 28. It did not work either. Right now, the main issue with any created emulator is that the emulator does not start at all. With the Processing-phone emulator, I get the error the first time I run it. However, the phone is launched after few seconds. 

At this point, I could try launching the (emu-echo) emulator manually. The problem I am having is that when I tried to invoke the command, the `emulator.exe -list-avds` in the **sdk/emulator** folder only sees emulator setup by AS (including the Processing-phone) but none of the emulators created by "Run configuration". I will need to figure this one out so I can launch emulators manually. 

Quick question: the port is associated to an emulator when it is launched using `emulator -avd -port -gpu` right? What values are you using?

**Comment by kfrajer** [comment]
I did a quick final test. I ran:

`d:\Program_Files\AndroidSDK\sdk\tools\bin\avdmanager create avd -n "emu-foxtrot" -c "64M" -k "system-images;android-28;google_apis;x86" -d "Nexus One" -p "C:\Users\C\Documents\Processing\android\avd\emu-foxtrot" -f`

and when I list the avd via avdmanager, I get the phone in the list:

```
d:\Program_Files\AndroidSDK\sdk\emulator\emulator.exe -list-avds
Nexus_9_API_26
Pixel_3_XL_API_26
emu-foxtrot
processing-phone
```
This is not related to the main problem, but I am trying to see if I can create a device and get it listed under "Run Configuration". I will try more tomorrow.

**Comment by kfrajer** [comment]
I was able to launch the sketch in the emulator but only for the Processing-phone emulator. You are right. I have platform 21, 26, 28 and the Processing-phone works for 26 and 28 but not for 21. When I tried to launch sketches when platform 21 is selected, you get the stack trace error I shared with you yesterday via email.

Now, I created a new emulator, emu-golf, a Nexus One with mage API26. I tried launching the sketch using platform 28 but the device does not open. I do not get a huge stack trace as before. In fact, here is what I get: 

> Build folder: C:\Users\C\AppData\Local\Temp\android6346414647149087724sketch
:app:preBuild UP-TO-DATE
:app:preDebugBuild
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:checkDebugManifest
:app:generateDebugBuildConfig
:app:prepareLintJar
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
:app:createDebugCompatibleScreenManifests
:app:processDebugManifest
:app:splitsDiscoveryTaskDebug
:app:processDebugResources
:app:generateDebugSources
:app:javaPreCompileDebug
:app:compileDebugJavaWithJavac
:app:compileDebugNdk NO-SOURCE
:app:compileDebugSources
:app:mergeDebugShaders
:app:compileDebugShaders
:app:generateDebugAssets
:app:mergeDebugAssets
:app:extractTryWithResourcesSupportJarDebug
:app:transformClassesWithStackFramesFixerForDebug
:app:transformClassesWithDesugarForDebug
:app:transformClassesWithDexBuilderForDebug
:app:transformDexArchiveWithExternalLibsDexMergerForDebug
:app:transformDexArchiveWithDexMergerForDebug
:app:mergeDebugJniLibFolders
:app:transformNativeLibsWithMergeJniLibsForDebug
:app:processDebugJavaRes NO-SOURCE
:app:transformResourcesWithMergeJavaResForDebug
:app:validateSigningDebug
:app:packageDebug
:app:assembleDebug

> BUILD SUCCESSFUL in 32s
28 actionable tasks: 28 executed
Emulator process exited with status 1.
EmulatorController: Emulator never booted. NOT_RUNNING
Error while starting the emulator. (NOT_RUNNING)
Shutting down any existing adb server... Done.

**Comment by kfrajer** [comment]
Ok, after I setup the env variables in the processBuilder as described here (but under the create device function in *AVD.java*) https://github.com/DeerajTheepshi/processing-android/issues/27#issuecomment-515717230 I was able to run a newly created emulator, so this should resolve the issue. Is there any reason to call `env.clean()` when defining a **processBuilder()** object?

**Comment by DeerajTheepshi** [comment]
Solved with displaying only platforms above 26 for selection and by removing env.clear()
