### ISSUE TITLE
Run Configuration only lists one device (only 1 of 2 connected)

### ISSUE THREAD

**Issue by kfrajer** [DeerajTheepshi/processing-android#30]
I have one device connected and the **Run Configuration** displays it as expected when I clicked the radial button. However, If I connect my tablet, it does show the tablet but it does not show my phone. While in the "Run Configuration" window, if I unplug the tablet, then the list updates and it shows my phone. Image attached when I connected my tablet (my second device)

![PDE-emu-avd-x1b-bug](https://user-images.githubusercontent.com/26076840/61605002-a558ea00-ac11-11e9-8a78-aa52afc71357.png)

**Comment by DeerajTheepshi** [comment]
Fixed on https://github.com/DeerajTheepshi/processing-android/pull/25
