### ISSUE TITLE
Truncated text in Automatic Dialog box

### ISSUE THREAD

**Issue by kfrajer** [DeerajTheepshi/processing-android#7]
Increase the dimensions of the dialog box so it display the full text for both the selected folder path and the buttons. I suggest to add the tool tip text feature to the Text Field for the selected folder path in case the selected path is too long. 

![mnual_download_PR2](https://user-images.githubusercontent.com/26076840/59210237-22a52f80-8b7b-11e9-9696-cb1f5eafa2de.png)

**Comment by DeerajTheepshi** [comment]
Completed with #2
